version: '0.2'
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo "Prebuild, installing npm dependencies"
      - npm install
  build:
   commands:
     # Builds Angular application
     - echo Build started on `date`
     - npm run build    
  post_build:
    commands:
     # Clear out the old contents in the bucket connected to CloudFronts
     - aws s3 rm s3://angular-demo-2021 --recursive
     - echo S3 bucket angular-demo-2021 is cleared.
     # Copy Angular build output (dist) folder to S3 bucket
     - aws s3 cp dist/angular-demo s3://angular-demo-2021 --recursive
     # Create CloudFront invalidation to clear CloudFront cache
     - aws cloudfront create-invalidation --distribution-id E9RJXL5EBYNDZ --paths "/*"
     - echo Build completed on `date`
artifacts:
  name: "BuildOutput"
  files:
    - '**/*'
  base-directory: 'dist/angular-demo'